[project]
name = "cli"
version = "0.1.0"
main-class = "com.jot.samples.cli.CliMain"
layout = "maven"

[toolchains]
java = "21"

[dependencies]
picocli = "info.picocli:picocli:4.7.6"

[test-dependencies]
junit = "org.junit.jupiter:junit-jupiter:5.11.0"
